.TH BATTERYCM-CHARGER 1 "2021-08-28" "1.2.0" "User Commands"
.SH NAME
batterycm-charger \- a charging threshold auxiliary adjustment tool
.SH SYNOPSIS
.B batterycm-charger
[
<\fIMIN\fR>
<\fIMAX\fR>
]
.SH DESCRIPTION
\fBbatterycm-charger\fP
is used by
\fIbatterycm-charger.service\fP
default.
But for
\fBHUAWEI\fP
notebooks users,
the arguments
\fI`MIN`\fP
and
\fI`MAX`\fP
are available for setting the
\fBcharging range\fP.
.SH SEE ALSO
\fBbatterycm-switcher\fP(1)
.SH BUGS
<https://github.com/supdrewin/batterycm-switcher/issues> 
.SH AUTHORS
Supdrewin
<https://github.com/supdrewin>
